### ISSUE TITLE
Invitation to join KotOR Engine Reimplementation Group Discord

### ISSUE THREAD

**Issue by lachjames** [KobaltBlu/KotOR.js#3]
Hi :)

This project looks very cool! I'm the leader of another K1/TSL engine reimplementation project ("Northern Lights", an Aurora Engine reimplementation), and I've got a Discord group where we can all talk shop.

Here's an invitation link if you're interested: https://discord.gg/QgRbEE

The invitation expires in a day, so if you want to join after that feel free to respond to this issue :)

Thanks, and again, great work on what seems to be a very cool project :)

**Comment by KobaltBlu** [comment]
Glad to see more people taking an interest in this topic.

Thanks for the invitation. I'll try to drop in sometime.

Best of luck on your project! 👍
