### ISSUE TITLE
Forge displays full folder path on mac instead of archive name

### ISSUE THREAD

**Issue by canderis** [KobaltBlu/KotOR.js#4]
<img width="497" alt="Screen Shot 2021-01-06 at 5 58 14 PM" src="https://user-images.githubusercontent.com/8195885/103837847-3368a080-5051-11eb-9e83-6c83a755876c.png">

**Comment by KobaltBlu** [comment]
Commit: https://github.com/KobaltBlu/KotOR.js/commit/e7a596fa9589a3332de9d46b4d652a9f2d93f3ce should fix this issue.

**Comment by KobaltBlu** [comment]
Ok I think I got them all now. Check out commit: https://github.com/KobaltBlu/KotOR.js/commit/0241f786ffdbe0245cbaa2e2404eaf7f6e0b01bd.
