### ISSUE TITLE
Project Wizard doesn't allow new folders to be made

### ISSUE THREAD

**Issue by canderis** [KobaltBlu/KotOR.js#5]
<img width="906" alt="Screen Shot 2021-01-18 at 11 18 29 AM" src="https://user-images.githubusercontent.com/8195885/104950984-48b1c900-5987-11eb-9a4e-7f61783916dc.png">

I believe there should be an electron param to enable this

**Comment by KobaltBlu** [comment]
You are right. I'll add it to the relevant dialogs.

**Comment by KobaltBlu** [comment]
Try the changes in https://github.com/KobaltBlu/KotOR.js/commit/93ec583fe6495173fc097508f6caede7dc0aebc6 and see if the problem persists.
