### ISSUE TITLE
New Project Wizard defaults to a location that does not exist

### ISSUE THREAD

**Issue by canderis** [KobaltBlu/KotOR.js#6]
<img width="602" alt="Screen Shot 2021-01-18 at 11 17 35 AM" src="https://user-images.githubusercontent.com/8195885/104951057-6f6fff80-5987-11eb-8a32-c3c5e76e517e.png">

It should default to a valid folder, or create these folders

**Comment by KobaltBlu** [comment]
I think creating the projects folder if it doesn't exist would be the best option.

**Comment by KobaltBlu** [comment]
https://github.com/KobaltBlu/KotOR.js/commit/faa3a183d0c5cfe717eae757a3a9d40b203a2f98 should fix this issue.
